version: '3.7'

services:
  web:
    build: .
    volumes:
      - yarn_cache:/yarn
      - node_modules_cache:/app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"

volumes:
  yarn_cache:
  node_modules_cache: